language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.4

matrix:
    fast_finish: true
env:
    - SYMFONY_VERSION=3.4.*

before_install:
    - curl -sSfL -o ~/.phpenv/versions/${TRAVIS_PHP_VERSION}/bin/phpunit https://phar.phpunit.de/phpunit-9.phar
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require doctrine/orm:^2.5 --no-update

install: composer install --prefer-dist --no-interaction

script: phpunit
